# Generated by Django 4.2.9 on 2024-01-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_photo',
            new_name='photo',
        ),
    ]
