# Generated by Django 4.2.9 on 2024-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_user_photo_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.productphoto'),
        ),
    ]
