# Generated by Django 4.2.9 on 2024-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(related_name='products', to='shop.productphoto'),
        ),
    ]
