# Generated by Django 4.2.9 on 2024-01-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_productphoto_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='desired_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Желаемое время доставки'),
        ),
    ]
